version: "3"

services:
  kics:
    user: "${CURRENT_UID}"
    platform: linux
    image: checkmarx/kics
    container_name: kics
    hostname: kics
    volumes:
      - ./:/path/
    build:
      context: ./
      dockerfile: Dockerfile
    command: -p /path/ -v
